config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "articles#index"
  resources :users, only: :show
  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
      collection do
        get 'search'
      end
  end
  get 'categories/index'
  resource :categories

end

app/models/article.rb
class Article < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  has_one_attached :image
  belongs_to :user
  has_many :comments

  enum status: { public: 0, private: 1 }, _prefix: true

  validates :article_name, length: { maximum: 20 }, presence: true
  validates :text, length: { maximum: 400 }, presence: true
  validates :category_id, numericality: { greater_than_or_equal_to:1 ,less_than_or_equal_to:11, message: "を選んでください" }
  validates :status, inclusion: { in: Article.statuses.keys }
  validates :image, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :redirect, only: [:edit, :destroy]
  before_action :set_category

  def index
    @categories = Category.all
    @articles = Article.status_public.order(created_at: :desc)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comments = @article.comments.includes(:user)
    @comment = Comment.new
    if @article.status_private? && @article.user != current_user
      redirect_to root_path
    end
  end

  def edit
 
  end

  def update
    if @article.update(article_params)
      redirect_to article_path
    else
      render :edit
    end
  end

  def destroy
    if @article.destroy
      redirect_to root_path
    end
  end

  def search
    # params[:q]がnilではない且つ、params[:q][:name]がnilではないとき（商品名の欄が入力されているとき）
    # if params[:q] && params[:q][:name]と同じような意味合い
    if params[:q]&.dig(:article_name)
      # squishメソッドで余分なスペースを削除する
      squished_keywords = params[:q][:article_name].squish
      ## 半角スペースを区切り文字として配列を生成し、paramsに入れる
      params[:q][:article_name_cont_any] = squished_keywords.split(" ")
    end
    @q = Article.ransack(params[:q])
    @articles = @q.result
  end

  private

  def article_params
    params.require(:article).permit(:article_name, :text, :category_id, :status, :image).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def set_category
    @categories = Category.all
  end

  def redirect
    unless current_user == @article.user
      redirect_to root_path
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class= "app">
  <%= render "shared/header" %>
  <div class="main">
    <%= render "shared/sidebar" %>
    <%= form_with model: @article, id: 'new_post', url: article_path, class: 'article-form-main',local: true do |f| %>
      <div class='article-form-wrap'>
        <div class='article-form-header'>
          <h1 class='article-form-header-text'>
            投稿を編集
          </h1>
        </div>

        <%= render 'shared/error_messages', model: f.object %> 

        <div class="article-form-group">
          <label class="user-form-text">状態</label> 
          <span class="indispensable">必須</span>
          <%= f.label(:pubulic, for: nil, class: 'article-status-label') do %>
            <%= f.radio_button :status, :public %>              <%= t ".public" %>
          <% end %>
          <%= f.label(:private, for: nil, class: 'article-status-label') do %>
            <%= f.radio_button :status, :private %>
            <%= t ".private"  %>
          <% end %>
        </div>

        <div class="article-form-group">
          <label class="article-form-text">投稿画像</label>
          <span class="indispensable">必須</span>
          <% if @article.image.present? %> 
            <%= image_tag @article.image , id: 'article-img' %>
          <% end %>
          <div id="previews"></div>
          <%= f.file_field :image, id: "article-image"%>
        </div>

        <div class="article-form-group">
          <label class="article-form-text">カテゴリー</label>
          <span class="indispensable">必須</span>
           <%= f.collection_select(:category_id,Category.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"article-category"}) %>
        </div>

        <div class="article-form-group">
          <label class="article-form-text">タイトル</label>
          <span class="indispensable">必須</span>
          <%= f.text_field :article_name, class: 'article-title', id:"article_text", placeholder: "20文字以内" %>
        </div>

        <div class="article-form-group">
          <label class="article-form-text">内容</label>
          <span class="indispensable">必須</span>
          <%= f.text_area :text, class: 'article-text', id:"item_text", placeholder: "400字以内" %>
        </div>

        <div class=" article-btn">
          <%= f.submit "編集する" , class: "article-blue-btn" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<div class= "app">
  <%= render "shared/header" %>
  <div class="main">
    <%= render "shared/sidebar" %>
    <div class='index-main'>
      <div class='index-contents'>
        <div class='index-sort'>
          <span class='index-sort-title'>新着投稿</span>
        </div>
        <ul class='index-article-lists'>
          <% @articles.each do |article| %>
              <li class='index-article-list'>
                <%= link_to article_path(article.id), method: :get do %>
                  <div class='article-content'>
                    <div class='article-img-content'>
                      <%= image_tag article.image, class: "article-img" if article.image.attached? %>
                    </div>
                    <div class='article-info-content'>
                      <div class='article-info'>
                        <div class='article-user-image'>
                          <%= image_tag article.user.image, id: "article-user-image" %>
                        </div>
                        <div class='article-name'>
                          <%= article.article_name %>
                        </div>
                      </div>
                      <div class='article-user-info'>
                        <div class='article-like-content'>
                          <div class='article-like'>
                            <i class="fa-solid fa-thumbs-up icon-like"></i>
                          </div>
                          <div class='article-like-count'>
                            <%= '5000000' %>
                          </div>
                        </div>
                        <div class='article-date-content'>
                          <div class='article-username'>
                            <%= article.user.username %>
                          </div>
                          <div class='article-date'>
                            <%= l article.created_at, format: :long %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
    <%= link_to(new_article_path, class: 'post-btn') do %>
      <i class="fa-solid fa-plus fa-2x fa-fw" style="color:white;"></i>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class= "app">
  <%= render "shared/header" %>
  <div class="main">
    <%= render "shared/sidebar" %>
    <%= form_with model: @article, id: 'new_post', url: articles_path, class: 'article-form-main', local: true do |f| %>
      <div class='article-form-wrap'>
        <div class='article-form-header'>
          <h1 class='article-form-header-text'>
            新しい投稿
          </h1>
        </div>

        <%= render 'shared/error_messages', model: f.object %> 

        <div class="article-form-group">
          <label class="user-form-text">状態</label> 
          <span class="indispensable">必須</span>
          <%= f.label(:pubulic, for: nil, class: 'article-status-label') do %>
            <%= f.radio_button :status, :public %>              <%= t ".public" %>
          <% end %>
          <%= f.label(:private, for: nil, class: 'article-status-label') do %>
            <%= f.radio_button :status, :private %>
            <%= t ".private"  %>
          <% end %>
        </div>

        <div class="article-form-group">
          <label class="article-form-text">投稿画像</label>
          <span class="indispensable">必須</span>
          <div id="previews"></div>
          <%= f.file_field :image, id: "article-image"%>
        </div>

        <div class="article-form-group">
          <label class="article-form-text">カテゴリー</label>
          <span class="indispensable">必須</span>
          <%= f.collection_select(:category_id,Category.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"article-category"}) %>
        </div>

        <div class="article-form-group">
          <label class="article-form-text">タイトル</label>
          <span class="indispensable">必須</span>
          <%= f.text_field :article_name, class: 'article-title', id:"article_text", placeholder: "20文字以内" %>
        </div>
       
        <div class="article-form-group">
          <label class="article-form-text">内容</label>
          <span class="indispensable">必須</span>
          <%= f.text_area :text, class: 'article-text', id:"item_text", placeholder: "400字以内" %>
        </div>

        <div class=" article-btn">
          <%= f.submit "投稿する" , class: "article-blue-btn" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/new3.html.erb
<div class= "app">
  <%= render "shared/header" %>
  <div class="main">
    <%= render "shared/sidebar" %>
    <div class="article-new-main">
    <div class="article-new-form-wrapper">

      <div class="form-top">
       新しい投稿
      </div>
      <%# 部分テンプレートでフォームを表示する %>
      <%= form_with model: @article, id: 'new_post',local: true do |f| %>
        <%= render 'shared/error_messages', model: f.object %> 

        <div class="post-field">
          <div class="field-flex">
            状態
            <span class="indispensable">必須</span>
            <%= f.label(:pubulic, for: nil, class: 'article-status-label') do %>
              <%= f.radio_button :status, :public %>
              <%= t ".public" %>
            <% end %>
            <%= f.label(:private, for: nil, class: 'article-status-label') do %>
              <%= f.radio_button :status, :private %>
              <%= t ".private"  %>
            <% end %>
            
          </div>
       </div>

       <div class="field">
         <div class="field-flex">
           投稿画像
           <span class="indispensable">必須</span>
         </div>
         <div id="previews"></div>
         <%= f.file_field :image, id: "article-image"%>
       </div>

       <div class="post-field">
         <div class="field-flex">
           カテゴリー
           <span class="indispensable">必須</span>
         </div>
         <%= f.collection_select(:category_id,Category.all, :id, :name, {}, {class:"select-box", id:"article-category"}) %>
       </div>

       <div class="post-field">
         <div class="field-flex">
           タイトル
           <span class="indispensable">必須</span>
         </div>
         <%= f.text_field :article_name, class: :form__title, id:"article_text",
           placeholder: "20文字以内" %>
       </div>
       
       <div class="post-field">
         <div class="field-flex">
           内容
           <span class="indispensable">必須</span>
         </div>
         <%= f.text_area :text, class: :form__text, id:"item_text",
           placeholder: "400字以内" %>
       </div>

       <div class="field">
         <%= f.submit "投稿する" , class: :form__btn %>
       </div>

      <% end %>
      

    </div>
  </div>
</div>
</div>

app/views/articles/search.html.erb
<div class= "app">
  <%= render "shared/header" %>
  <div class="main">
    <%= render "shared/sidebar" %>
    <div class='index-main'>
      <div class='index-contents'>
        <div class='index-sort'>
          <span class='index-sort-title'>検索結果 <%= @articles.count %> 件</span>
        </div>
        <ul class='index-article-lists'>
          <% @articles.each do |article| %>
              <li class='index-article-list'>
                <%= link_to article_path(article.id), method: :get do %>
                  <div class='article-content'>
                    <div class='article-img-content'>
                      <%= image_tag article.image, class: "article-img" if article.image.attached? %>
                    </div>
                    <div class='article-info-content'>
                      <div class='article-info'>
                        <div class='article-user-image'>
                          <%= image_tag article.user.image, id: "article-user-image" %>
                        </div>
                        <div class='article-name'>
                          <%= article.article_name %>
                        </div>
                      </div>
                      <div class='article-user-info'>
                        <div class='article-like-content'>
                          <div class='article-like'>
                            <i class="fa-solid fa-thumbs-up icon-like"></i>
                          </div>
                          <div class='article-like-count'>
                            <%= '5000000' %>
                          </div>
                        </div>
                        <div class='article-date-content'>
                          <div class='article-username'>
                            <%= article.user.username %>
                          </div>
                          <div class='article-date'>
                            <%= l article.created_at, format: :long %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </li>
          <% end %>
        </ul>
      </div>
      <div class='item-contents' id="detailed-search-result-wrapper">
        <%= search_form_for @q, url: search_articles_path, html: {id: "detailed-search-form"} do |f| %>
          <div class="search-field">
            <%= f.label :category_id_in, 'カテゴリ' %>
            <br>
            <%= f.collection_check_boxes(:category_id_in, Category.all, :id, :name, {include_blank: "---"}) %>
         </div>
         <%= f.submit '検索' %>
        <% end %>
      </div>
    </div>
    <%= link_to(new_article_path, class: 'post-btn') do %>
      <i class="fa-solid fa-plus fa-2x fa-fw" style="color:white;"></i>
    <% end %>
  </div>
 

</div>

app/views/articles/show.html.erb
<div class= "app">
  <%= render "shared/header" %>
  <div class="main">
    <%= render "shared/sidebar" %>
    <div class="article-show-main">
      <div class="article-show-category">
        <%= @article.category.name %>
      </div>
      <div class='article-show-user-info'>
        <% if user_signed_in? && current_user.id == @article.user_id %>
          <% if @article.status_private? %>
            <div class='article-show-article-private'>
              <%= t ".private" %>
            </div>
          <% else @article.status_public? %>
            <div class='article-show-article-public'>
              <%= t ".public" %>
            </div>
          <% end %>
        <% end %>
        <div class='article-show-user-image'>
          <%= link_to (image_tag @article.user.image, class: "article-show-user-img"), user_path(@article.user.id) %>
        </div>
        <div class='article-show-user-data'>
          <div class='article-show-user-name'>
            <%= link_to  @article.user.username, user_path(@article.user.id), class: "article-show-username" %>
          </div>
          <div class='article-show-article-date'>
            <%= l @article.created_at, format: :long %>
          </div>
        </div>
        <div class="article-show-navi">
          <% if user_signed_in? && current_user.id == @article.user_id %>
            <%= link_to "編集", edit_article_path(@article.id), method: :get, class: "article-edit-btn" %>
            <%= link_to "削除", article_path(@article.id), method: :delete, class:"article-destroy-btn" %>
          <% end %>
        </div>
      </div>
      <div class="article-show-title">
        <h2 class="article-show-name">
          <%= @article.article_name %>
        </h2>
      </div>
      <div class="article-show-img-box">
        <div class="article-show-img-content">
          <%= image_tag @article.image ,class:"article-show-box-img" %>
        </div>
      </div>
      <div class="article-show-explain-box">
        <span><%= simple_format(@article.text) %></span>
      </div>
      
      <div id="article-show-comments">
        <h4 class="article-show-comment-title">
          コメント(<%= @article.comments.count %>)
        </h4>
        <% @article.comments.each do |comment| %>
          <div class='article-show-comment-contents'>
            <div class='article-show-comment-image'>
              <%= link_to (image_tag comment.user.image, id: "article-show-comment-image"), user_path(comment.user.id) %>
            </div>
            <div class='article-show-comment-info'>
              <%=link_to comment.user.username, user_path(comment.user.id), class: 'article-show-comment-username' %>
              <div class='article-show-comment-box'>
                <div class='article-show-comment-field'>
                  <div class='article-show-comment'><%= comment.text %></div>
                  <div class="article-show-comment-destroy">
                    <% if user_signed_in? && current_user.id == comment.user.id %>
                      <%= link_to "削除", article_comment_path(comment.article.id, comment.id), method: :delete, class: "article-show-comment-destroy-btn",id: "article-show-comment-destroy-btn" %>
                    <% end %>
                  </div>
                </div>
                <div class='article-show-comment-date'><%= l comment.created_at, format: :long, id: "article-show-comment-date" %></div>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <div class="article-show-comment-form">
        <% if user_signed_in? %>
          <%= form_with model: [@article, @comment], id: "article-show-comment-form" do |f| %>
            <div class="article-show-comment-form-image">
              <%= image_tag current_user.image, id: "article-show-comment-form-image" %>
            </div>
            <div class="article-show-comment-form-box">
              <%= f.text_area :text , class: "article-show-comment-text", placeholder: 'コメントする'%>
              <%= button_tag type: "submit", class: "article-show-comment-btn", id: "article-show-comment-btn" do %>
                <i class="fa-solid fa-share fa-2x" style="color:black;"></i>
              <% end%>
            </div>
          <% end %>
        <% else %>
          <div id="article-show-comment-form">
            <div class="article-show-comment-form-image">
              <%= image_tag "default.png", id: "article-show-comment-form-image" %>
            </div>
            <div class="article-show-comment-form-login">
              <%= link_to "ログインしてコメントする", new_user_session_path, class: "article-show-comment-login-btn" %>
            </div>
          </div>
        <% end %>
      </div>
       <%#div class="comment-box">
         <form>
         <textarea class="comment-text"></textarea>
         <p class="comment-warn">
          相手のことを考え丁寧なコメントを心がけましょう。
          <br>
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        </p>
        <button type="submit" class="comment-btn">
          <%#= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
          <%#span>コメントする<span>
         </button>
        </form>
      </div%>
    </div>
  </div>
</div>