config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "articles#index"
  resources :users, only: :show
  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
      collection do
        get 'search'
      end
  end
  get 'categories/index'
  resource :categories

end

app/views/shared/_articles.html.erb
 <div class="item">
      <%#= link_to image_tag( @articles.image , class: :item__img ),  article_path(articles.id)%> 
      
      <div class="item__body">  
           <%# ログインの有無でお気に入り機能の動作を変える %>     
           <% if user_signed_in? %>

                <%# お気に入りの有無でお気に入り機能の表示を変える %>
                <% if current_user.favorited?(items) %>
                        <%= link_to item_favorites_path(items), method: :delete do %>
                           <span class="item__favorite">❤️</span>
                           <span class="favorite__count"><%= items.favorites.count %></span>
                        <% end %>
                  <% else %>
                        <%= link_to item_favorites_path(items), method: :post do %>
                            <span class="item__favorite">🤍</span>
                            <span class="favorite__count"><%= items.favorites.count %></span>
                        <% end %>
                  <% end %>
                  <%# /お気に入りの有無でお気に入り機能の表示を変える %>

           <% else %>
                  <%=link_to '🤍', new_user_session_path, class: :item__favorite %>
           <% end %>
          <%# /ログインの有無でお気に入り機能の表示を変える %>

        <%# ユーザー名の文字数で表示を変える %>
            <%# if @articles.user.username.length <= 8  %>
                <%#= link_to articles.user.username , user_path(articles.user_id), class: :item__user__under %>
                <%#= image_tag "click.png", class: "go_link__user" %>
            <%# else %>
                <%#= link_to articles.user.username , user_path(articles.user_id), class: :item__user__over %>
                <%#= image_tag "click.png", class: "go_link__user" %>
            <%# end %>
        <%# /ユーザー名の文字数で表示を変える %>
        
    </div>
 </div>  

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%# 呼び出す時は以下を使用 %>
<%#= render 'shared/error_messages', model: f.object %> 

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるフリマアプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%#= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
    <%#= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>Little Gardenについて</h2>
      <ul>
        <li><%#= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%#= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%#= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%#= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>Little Gardenを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>Littele Gardenについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("logo.png", class:"logo-white"), "#" %>
  <p>© Littele Garden</p>
</div>

app/views/shared/_form.html.erb
<%= form_with model: @article, id: 'new_post',local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %> 

  <div class="post-field">
    <div class="field-flex">
      <%= f.label(:pubulic, for: nil, class: 'article-status-label') do %>
        <%= f.radio_button :status, :public %>
        <%= I18n.t('activerecord.attributes.article.statuses.public') %>
      <% end %>
      <%= f.label(:private, for: nil, class: 'article-status-label') do %>
        <%= f.radio_button :status, :private %>
        <%= I18n.t('activerecord.attributes.article.statuses.private') %>
      <% end %>
      <span class="indispensable">必須</span>
    </div>
  </div>

  <div class="post-field">
    <div class="field-flex">
      <%= f.label :text, "カテゴリー"%>
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:category_id,Category.all, :id, :name, {}, {class:"select-box", id:"article-category"}) %>
  </div>

  <div class="field">
    <div class="field-flex">
      <%= f.label :image, "画像" %>
      <span class="indispensable">必須</span>
    </div>
    <div id="previews"></div>
    <%= f.file_field :image %>
  </div>

  <div class="post-field">
    <div class="field-flex">
      <%= f.label :text, "内容"%>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :text, class: :form__text, id:"item_text",
                           placeholder: "作っている時のつぶやきや表情はどんな風に見えましたか？
１年後、５年後・・お子さんが大きくなった時にも残しておきたい成長の記録をぜひ残してください！" %>
  </div>

  <div class="field">
    <%= f.submit "投稿する" , class: :form__btn %>
  </div>

<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class="header">
  <div class="left-header">
    <div class="header-app-icon">
      <%= link_to (image_tag "logo.png", class:"logo-img") , "/" %>
    </div>
    <div class='header-search-contents'>

      <%= search_form_for Article.ransack(params[:q]), url: search_articles_path, html: {class: "header-search-form"} do |f| %>
        <button class="header-search-button">
          <div class="header-search-icon" >
          <i class="fa-solid fa-magnifying-glass" style="color:grey;"></i>
          </div>
        </button>
        <%= f.text_field :article_name, placeholder: 'タイトルから検索', class: 'header-input-box' %>
        <br>
        <%= f.label :submit, class: "search-button", style: "display: none;" do %>
          <input type="submit" value="検索" class="send">
          <%= f.submit :submit, id: "q_submit", style: "display: none;"%>
        <% end %>
      <% end %>

 
    </div>
  </div>

  <div class="center-header">
    <ul class="header-menu">
      <li>
        <div class="header-icons" id="home-btn">
          <%= link_to root_path do %>
            <i class="fa-solid fa-house fa-2x fa-fw icon-a" style="color:black;"></i>
          <% end %>
        </div>
        <div class="header-nav hidden" id="pull-down">
          <span>ホーム</span>
        </div>
      </li>
      <li>
        <div class="header-icons" id="category-btn">
          <i class="fa-solid fa-tags fa-2x fa-fw icon-a" style="color:black;"></i>
        </div>
        <div class="header-nav2 hidden" id="pull-down2">
          <span>カテゴリー</span>
        </div>
      </li>
      <li>
        <div class="header-icons" id="glossary-btn">
          <%= link_to root_path do %>
            <i class="fa-solid fa-spell-check fa-2x fa-fw icon-a" style="color:black;"></i>
          <% end %>
        </div>
        <div class="header-nav3 hidden" id="pull-down3">
          <span>用語集</span>
        </div>
      </li>
      <li>
        <div class="header-icons" id="q-btn">
          <%= link_to root_path do %>
            <i class="fa-solid fa-clipboard-question fa-2x fa-fw icon-a" style="color:black;"></i>
          <% end %>
        </div>
        <div class="header-nav4 hidden" id="pull-down4">
          <span>質問掲示板</span>
        </div>
      </li>
    </ul>
    <ul class="category-lists" id="categories">
      <% @categories.each do |category| %>
        <li class="category-list">
          <%= link_to category.name, categories_index_path(category.id), class: "category-text" %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class='right-header'>
    <ul class='account-info'>
          <%# ログイン時の表示 %>
          <% if user_signed_in? %>
              <% if current_user.image.present?%>
                <li>
                  <div class="header-user-image" id="header-user-btn">
                    <%= link_to (image_tag current_user.image, class: "header-user-image"), user_path(current_user) %>
                  <div class="header-nav5 hidden" id="pull-down5">
                    <%= current_user.username %> 
                  </div>
                </li>
              <% else %>
                <li><%= link_to (image_tag "default.png", class: "header-user-image"),  user_path(current_user) %></li>
              <% end %>
            <li>
              <div class="logout-image" id="logout-btn">
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa-solid fa-arrow-right-from-bracket fa-2x icon-a" style="color:black;"></i>
                <% end %>
              </div>
              <div class="header-nav6 hidden" id="pull-down6">
                <%= "ログアウト" %> 
              </div>
            </li>
          <%# /ログインの時 %>
          <% else %>
          <%# 未ログイン時の表示 %>
            <li>
              <div class="signup-image" id="signup-btn">
                <%= link_to new_user_registration_path do %>
                  <i class="fa-solid fa-user-plus fa-2x fa-fw" style="color:black;"></i>
                <% end %>
              </div>
              <div class="header-nav7 hidden" id="pull-down7">
                <span>新規登録</span>
              </div>
            </li>
            <li>
              <div class="login-image" id="login-btn">
                <%= link_to new_user_session_path do %>
                  <i class="fa-solid fa-arrow-right-to-bracket fa-2x fa-fw" style="color:black;"></i>
                <% end %>
              </div>
              <div class="header-nav8 hidden" id="pull-down8">
                <span>ログイン</span>
              </div>
            </li>
          <% end %>
          <%# /未ログイン時の表示 %>
    </ul>
  </div>
</header>

app/views/shared/_header2.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class="top-page-header">
  <div class="little-garden-icon">
    <%= link_to (image_tag "logo.png", class:"logo-pc") , "/" %>
    <%#= link_to (image_tag "logo_responsive.png", class:"logo__mobile") , root_path %>
  </div>
  <div class='search-bar-contents'>
    <form class="search-form" action="#">
      <button class="search-button">
        <div class="search-icon" %>
        <i class="fa-solid fa-magnifying-glass" style="color:grey;"></i>
        </div>
      </button>
      <input class='input-box' placeholder='キーワードで検索'>
    </form>
    <ul class='lists-left'>
      <li><div class="menu-list" id="mypage-btn">MENU</div></li>
        <% if user_signed_in? %>
          <ul class="show-lists hidden" id="pull-down">
            <li><%= link_to"サイトについて", "#" ,class: "pull-down-list" %></li>
            <li><%= link_to"マイページ", user_path(current_user) ,class: "pull-down-list" %></li>
            <li><%= link_to"投稿する", new_article_path,class: "pull-down-list" %></li>
            <li><%= link_to"設定", edit_user_registration_path, class: "pull-down-list" %></li>
            <li><%= link_to"ログアウト", destroy_user_session_path, method: :delete, class: "pull-down-list" %></li>
          </ul>
        <% else %>
          <ul class="show-lists hidden" id="pull-down">
            <li><%= link_to"サイトについて", "#" ,class: "pull-down-list" %></li>
            <li><%= link_to"マイページ", new_user_session_path ,class: "pull-down-list" %></li>
            <li><%= link_to"投稿する", new_user_session_path ,class: "pull-down-list" %></li>
            <li><%= link_to"設定", new_user_session_path, class: "pull-down-list" %></li>
            <li><%= link_to"ログアウト", new_user_session_path, class: "pull-down-list" %></li>
          </ul>
        <% end %>

      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%= link_to 'Q&A', "#", class: "q-and-a-list" %></li>
    </ul>
  </div>
  <div class='navi'>
    <ul class='nav-right'>
          <%# ログイン時の表示 %>
          <% if user_signed_in? %>
            <li><%= link_to  current_user.username, "/users/#{current_user.id}", class: "header-user-name" %></li>
              <% if current_user.image.present?%>
                <li><%= link_to (image_tag current_user.image, class: "header-user-img"), "#" %></li>
              <% else %>
                <li><%= link_to (image_tag "default.png", class: "header-user-img"), "#" %></li>
              <% end %>
            <li><%= link_to"ログアウト", destroy_user_session_path, method: :delete, class: "log-out-btn" %></li>
            <%# PC表示 %>
        
             <%# /PC表示 %>

            <%# mobile表示 %>
            <li><div class="nav-mobile">
              <%= image_tag "menu.png", id: "mypage-btn-mobile" %>
            </div></li>
            <%# /mobile表示 %>
            
           
          <%# /ログインの時 %>
          <% else %>
          <%# 未ログイン時の表示 %>
            <li><%= link_to "新規登録", new_user_registration_path, class: "sign-up-btn" %></li>
            <li><%= link_to "ログイン", new_user_session_path, class: "log-in-btn" %></li>
          <% end %>
          <%# /未ログイン時の表示 %>
    </ul>
  </div>
</header>

app/views/shared/_index.html.erb
<div class='article-main'>
  <div class='article-contents'>
    <h2 class='title'>新着投稿</h2>
    <ul class='article-lists'>
      <% @articles.each do |article| %>
      <li class='list'>
      <%= link_to article_path(article.id), method: :get do %>
        <div class='article-img-content'>
          <%= image_tag article.image, class: "article-img" if article.image.attached? %>
        </div>
        <div class='article-info'>
          <h3 class='article-name'>
            <%= article.article_name %>
          </h3>
        </div>
      <% end %>
      <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    
    <%= link_to image_tag("logo.png", class:"second-fotter-logo"), "/" %>
    <p class='second-fotter-text'>© Littele Garden</p>
  </div>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo.png", class:"second-logo"), "/" %>
</header>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
 <div class='sidebar-main'>
    <ul class='sidebar-menu'>
          <% if user_signed_in? %>
            <% if current_user.image.present?%>
              <li class="sidebar-user-name-box">
                <%= link_to user_path(current_user) do %>
                  <div class="user-name-image" id="user-name-btn">
                    <%= image_tag current_user.image, id: "user-name-image" %>
                  </div> 
                  <span class="sidebar-user-name"><%= current_user.username %></span>
                 <% end %>
              </li>
            <% else %>
              <li class="sidebar-user-name-box">
                <%= link_to user_path(current_user) do %>
                  <div class="user-name-image" id="user-name-btn">
                    <%= image_tag "default.png", id: "user-name-image" %>
                  </div> 
                  <span class="sidebar-user-name"><%= current_user.username %></span>
                 <% end %>
              </li>
            <% end %>
            <li class="sidebar-user-room-box" >
              <%= link_to user_path(current_user) do %>
                <div class="user-room-image" id="user-room-btn">
                  <i class="fa-solid fa-door-open fa-2x" style="color:black;"></i>
                </div>
                <span class="sidebar-user-room">My Room</span>
              <% end %>
            </li>
            <li class="sidebar-user-follow-box" >
              <%= link_to "#" do %>
                <div class="user-follow-image" id="user-list-btn">
                  <i class="fa-solid fa-user-group fa-2x" style="color:black;"></i>
                </div>
                <span class="sidebar-user-follow">フォロー</span>
              <% end %>
            </li>
            <li class="sidebar-user-star-box" >
              <%= link_to "#" do %>
                <div class="user-star-image" id="user-star-btn">
                  <i class="fa-regular fa-star fa-2x" style="color:black;"></i>
                </div>
                <span class="sidebar-user-star">お気に入り</span>
              <% end %>
            </li>
            <li class="sidebar-user-edit-box" >
              <%= link_to edit_user_registration_path do %>
                <div class="user-edit-image" id="user-edit-btn">
                  <i class="fa-solid fa-user-pen fa-2x" style="color:black;"></i>
                </div>
                <span class="sidebar-user-edit">ユーザー編集</span>
              <% end %>
            </li>
          <% else %>
            <li class="sidebar-user-name-box">
              <%= link_to new_user_session_path do %>
                <div class="user-name-image" id="user-room-btn">
                  <%= image_tag "default.png", id: "user-name-image" %>
                </div> 
                <span class="sidebar-user-name">ゲスト</span>
              <% end %>
            </li>
            <li class="sidebar-user-room-box" >
              <%= link_to new_user_session_path do %>
                <div class="user-room-image" id="user-room-btn">
                  <i class="fa-solid fa-door-open fa-2x" style="color:black;"></i>
                </div>
                <span class="sidebar-user-room">My Room</span>
              <% end %>
            </li>
            <li class="sidebar-user-follow-box" >
              <%= link_to new_user_session_path do %>
                <div class="user-follow-image" id="user-list-btn">
                  <i class="fa-solid fa-user-group fa-2x" style="color:black;"></i>
                </div>
                <span class="sidebar-user-follow">フォロー</span>
              <% end %>
            </li>
            <li class="sidebar-user-star-box" >
              <%= link_to new_user_session_path do %>
                <div class="user-star-image" id="user-star-btn">
                  <i class="fa-regular fa-star fa-2x" style="color:black;"></i>
                </div>
                <span class="sidebar-user-star">お気に入り</span>
              <% end %>
            </li>
            <li class="sidebar-user-edit-box" >
              <%= link_to new_user_session_path do %>
                <div class="user-edit-image" id="user-edit-btn">
                  <i class="fa-solid fa-user-pen fa-2x" style="color:black;"></i>
                </div>
                <span class="sidebar-user-edit">ユーザー編集</span>
              <% end %>
            </li>
          <% end %>
    </ul>
  </div>
</div>